FORMAT: 1A
HOST: http://api.anycook.de

# anycook
anycook is the online cookbook.

# Group Autocomplete
Ressources that autocomplete query strings.

## General [/autocomplete?query={query}&excludedCategory={excludedCategory}&excludedIngredients={excludedIngredients}&excludedTags={excludedTags}&excludedUsers={excludedUsers}&maxResults={maxResults}]
Autocompletes a query for all types

### Autocomplete query [GET] 

+ Parameters
    + query (string, `t`) ... String that should be completed
    + excludedCategory (optional, string, `Fleisch`) ... Excludes a category from autocomplete results
    + excludedIngredients (optional, string, `Kaffee,Saft`) ... Excludes one or more ingredients from autocomplete results (comma seperated)
    + excludedTags (optional, string, `matschepampe,weihnachten`) ... Excludes on or more tags from autocomplete (comma seperated)
    + excludedUsers (optional, string, `1,2`) ... List of user ids to exclude (only numbers, comma seperated)
    + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results 

+ Response 200 (application/json)

        { 
            "tags":["japanisch","joghurt"],
            "kategorien":[],
            "zutaten":["Joghurt"],
            "user":[
                {"id":24,"name":"jaminka"},
                {"id":83,"name":"jasmin"},
                {"id":60,"name":"Johänni"}],
            "gerichte":["Johannisbeer-Blechkuchen"]
        }

## Ingredient [/autocomplete/ingredient?query={query}&exclude={exclude}&maxResults={maxResults}]
Autocompletes only ingredient names

### Autocomplete query [GET]

+ Parameters
   + query (string, `l`) ... String that should be completed
   + exclude (optional, string, `Kaffee,Saft`) ... Excludes one or more ingredients from autocomplete results (comma seperated)
   + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results

+ Response 200 (application/json)
        
        ["Lasagneplatten","Lauch","Lauchzwiebel","Lauchzwiebeln","lauwarmes Wasser","Linsen","Loffelbiscuits"]

## Tag [/autocomplete/tag?query={query}&exclude={exclude}&maxResults={maxResults}]
Autocompletes only tag names

### Autocomplete query [GET]

+ Parameters
   + query (string, `m`) ... String that should be completed
   + exclude (optional, string, `mexikanisch,weihnachten`) ... Excludes one or more tags from autocomplete results (comma seperated)
   + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results

+ Response 200 (application/json)
        
        ["matschepampe","mediteran","mexikanisch","minze"]

## User [/autocomplete/user?query={query}&exclude={exclude}&maxResults={maxResults}]
Autocompletes only user names

### Autocomplete query [GET]

+ Parameters
   + query (string, `j`) ... String that should be completed
   + exclude (optional, string, `1,2`) ... List of user ids to exclude (only numbers, comma seperated)
   + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results

+ Response 200 (application/json)
        
            [
                {"id":24,"name":"jaminka"},
                {"id":83,"name":"jasmin"},
                {"id":60,"name":"Johänni"}
            ]


# Group Category
Ressources that represent the recipe categories

## Categories [/category?sorted={sorted}]
Returns all category names with number of recipes. Sorted by name or in the anycook prefered order.

### Get all categories [GET]

+ Parameters
    + sorted (boolean, optional, `true`)
        If set to true categories get sorted in the anycook prefered order.

+ Response 200 (application/json)

        {
            "Grundrezepte":0,
            "Vorspeisen und Häppchen":0,
            "Gemüse und Salate":18,
            "Suppen und Eintöpfe":15,
            "Fleisch":17,
            "Fisch":3,
            "Nudeln und Reis":24,
            "Kartoffelgerichte":4,
            "Ofengerichte":22,
            "Eierspeisen":4,
            "Soßen und Dips":5,
            "Kuchen und Torten":0,
            "Backwaren":6,
            "Desserts":46,
            "Sonstiges":0
        }


## Category [/category/{name}]
Returns a category with a list of its recipes.

### Get category [GET]

+ Parameters
    + name (string, required, `Fleisch`) ... Name of a category.
    
+ Response 200 (application/json)

        {
            "name":"Fleisch",
            "recipes":["Yakitori","Hühnerfrikassee","Wiener Schnitzel mit Pommes","Sandwich mit Minutensteak","Hühnerbrust mit Erdnusssoße","Kebab im Teigmantel","gefüllte Hackbuletten","Schweinekotelett mit Sauerkraut","Hack-Gemüsetaschen","Putenpfanne mit Spinat und Kichererbsen","Hamburger","Gebratene Ente","Schinken-Käse-Brötchen","Gefüllte Paprika mit Hackfleisch","Pute mit Parmesan und Schinken","Hähnchenbrust mit Mandelkruste","Cordon bleu"],
            "recipeNumber":17
        }
