FORMAT: 1A
HOST: http://api.anycook.de

# anycook
anycook is the online cookbook.

# Group Autocomplete
Ressources that autocomplete query strings.

## General [/autocomplete?query={query}&excludedCategory={excludedCategory}&excludedIngredients={excludedIngredients}&excludedTags={excludedTags}&excludedUsers={excludedUsers}&maxResults={maxResults}]
Autocompletes a query for all types

### Autocomplete query [GET] 

+ Parameters
    + query (string, `t`) ... String that should be completed
    + excludedCategory (optional, string, `Fleisch`) ... Excludes a category from autocomplete results
    + excludedIngredients (optional, string, `Kaffee,Saft`) ... Excludes one or more ingredients from autocomplete results (comma seperated)
    + excludedTags (optional, string, `matschepampe,weihnachten`) ... Excludes on or more tags from autocomplete (comma seperated)
    + excludedUsers (optional, string, `1,2`) ... List of user ids to exclude (only numbers, comma seperated)
    + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results 

+ Response 200 (application/json)

        { 
            "recipes":["Johannisbeer-Blechkuchen"],
            "ingredients":["Joghurt"],
            "categories":[],
            "tags":["japanisch","joghurt"],
            "user":[
                {"id":24,"name":"jaminka"},
                {"id":83,"name":"jasmin"},
                {"id":60,"name":"Johänni"}]
            
        }

## Ingredient [/autocomplete/ingredient?query={query}&exclude={exclude}&maxResults={maxResults}]
Autocompletes only ingredient names

### Autocomplete query [GET]

+ Parameters
   + query (string, `l`) ... String that should be completed
   + exclude (optional, string, `Kaffee,Saft`) ... Excludes one or more ingredients from autocomplete results (comma seperated)
   + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results

+ Response 200 (application/json)
        
        [
            {"name":"Lasagneplatten"},
            {"name":"Lauch"},
            {"name":"Lauchzwiebel"},
            {"name":"Lauchzwiebeln"},
            {"name":"lauwarmes Wasser"},
            {"name":"Linsen"},
            {"name":"Loffelbiscuits"}
        ]

## Tag [/autocomplete/tag?query={query}&exclude={exclude}&maxResults={maxResults}]
Autocompletes only tag names

### Autocomplete query [GET]

+ Parameters
   + query (string, `m`) ... String that should be completed
   + exclude (optional, string, `mexikanisch,weihnachten`) ... Excludes one or more tags from autocomplete results (comma seperated)
   + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results

+ Response 200 (application/json)
        
        [
            {"name":"matschepampe"},
            {"name":"mediteran"},
            {"name":"mexikanisch"},
            {"name":"minze"}
        ]

## User [/autocomplete/user?query={query}&exclude={exclude}&maxResults={maxResults}]
Autocompletes only user names

### Autocomplete query [GET]

+ Parameters
   + query (string, `j`) ... String that should be completed
   + exclude (optional, string, `1,2`) ... List of user ids to exclude (only numbers, comma seperated)
   + maxResults = `10` (optional, number, `100`) ... Maximum number of the returned results

+ Response 200 (application/json)
        
            [
                {"id":24,"name":"jaminka"},
                {"id":83,"name":"jasmin"},
                {"id":60,"name":"Johänni"}
            ]


# Group Category
Ressources that represent the recipe categories

## Categories [/category?sorted={sorted}]
Returns all category names with number of recipes. Sorted by name or in the anycook prefered order.

### Get all categories [GET]

+ Parameters
    + sorted (boolean, optional, `true`)
        If set to true categories get sorted in the anycook prefered order.

+ Response 200 (application/json)

        [ 
            {
               "name" : "Backwaren",
               "recipeNumber" : 6,
               "sortId" : 13
            }, {
               "name" : "Desserts",
               "recipeNumber" : 46,
               "sortId" : 14
            }, {
               "name" : "Eierspeisen",
               "recipeNumber" : 3,
               "sortId" : 10
            }, {
               "name" : "Fisch",
               "recipeNumber" : 3,
               "sortId" : 6
            }
        ]


## Category [/category/{name}]
Returns a category with a list of its recipes.

### Get category [GET]

+ Parameters
    + name (string, required, `Fleisch`) ... Name of a category.
    
+ Response 200 (application/json)

        {
            "name":"Fleisch",
            "recipeNumber":17,
            "sortId":1
        }
        

# Group Discover
Ressources that return list of recipes by different kind of recommendation types

## Discover [/discover?recipeNumber={recipeNumber}]
Returns all discover types

### Get [GET]

+ Parameters
    + recipeNumber = `30` (number, optional) ... Maximum number of returned recipes
    
+ Response 200 (application/json)
    
        {
            "newest" : [ 
                {
                    "description" : "ads asd asd asd ",
                    "image" : {
                        "big" : "http://10.1.0.200/images/recipe/big/category/fleisch.png",
                        "original" : "http://10.1.0.200/images/recipe/original/category/fleisch.png",
                        "small" : "http://10.1.0.200/images/recipe/small/category/fleisch.png"
                    },
                    "name" : "adsad asd ",
                    "tasteNum" : 0,
                    "time" : {
                        "std" : 2,
                        "min" : 0
                    }
                }, {
                    "description" : "Laoas",
                    "image" : {
                        "big" : "http://10.1.0.200/images/recipe/big/category/fisch.png",
                        "original" : "http://10.1.0.200/images/recipe/original/category/fisch.png",
                        "small" : "http://10.1.0.200/images/recipe/small/category/fisch.png"
                    },
                    "name" : "Hallo, ein Test",
                    "time" : {
                        "std" : 1,
                        "min" : 0
                    } 
                } 
            ],
            "recommended" : [ 
                {
                    "description" : "Gazpacho ist eine spanische kalte Suppe aus ungekochtem Gemüse.\nSie stammt aus Andalusien.\nDie ursprüngliche Suppe geht auf die Mauren zurück und war eine weiße Knoblauchsuppe aus Brot, Knoblauch, Olivenöl, Essig, Salz und Wasser.",
                    "image" : {
                        "big" : "http://10.1.0.200/images/recipe/big/category/suppen_und_eintoepfe.png",
                        "original" : "http://10.1.0.200/images/recipe/original/category/suppen_und_eintoepfe.png",
                        "small" : "http://10.1.0.200/images/recipe/small/category/suppen_und_eintoepfe.png"
                    },
                    "name" : "scharfes Gazpacho",
                    "time" : {
                        "std" : 0,
                        "min" : 10
                    }
                }, {
                    "description" : "Dies ist eine kleine Beischreibung",
                    "image" : {
                        "big" : "http://10.1.0.200/images/recipe/big/00TBQc8adqSIzMU3jDzz.png",
                        "original" : "http://10.1.0.200/images/recipe/original/00TBQc8adqSIzMU3jDzz.png",
                        "small" : "http://10.1.0.200/images/recipe/small/00TBQc8adqSIzMU3jDzz.png"
                    },
                    "name" : "Schokibakuchen",
                    "tasteNum" : 2,
                    "time" : {
                        "std" : 1,
                        "min" : 0
                    }
                } 
            ],
           "tasty" : [ 
                {
                    "description" : "Ein süßer Brotteig, der zu einem süßen Frühstück super passt oder auch als Kuchen verspeist werden kann.",
                    "image" : {
                        "big" : "http://10.1.0.200/images/recipe/big/5UFTaVg5Y1ubbGGuDT3V.png",
                        "original" : "http://10.1.0.200/images/recipe/original/5UFTaVg5Y1ubbGGuDT3V.png",
                        "small" : "http://10.1.0.200/images/recipe/small/5UFTaVg5Y1ubbGGuDT3V.png"
                    },
                    "name" : "Bananenbrot",
                    "tasteNum" : 0,
                    "time" : {
                        "std" : 1,
                        "min" : 0
                    }
                }, {
                    "description" : "Perfekt wenn man mal seinen Gästen was anbieten will, aber keine Zeit oder Lust hat sich groß zu engagieren!",
                    "image" : {
                        "big" : "http://10.1.0.200/images/recipe/big/vGuatfqNOsHb1M9CL4Cp.png",
                        "original" : "http://10.1.0.200/images/recipe/original/vGuatfqNOsHb1M9CL4Cp.png",
                        "small" : "http://10.1.0.200/images/recipe/small/vGuatfqNOsHb1M9CL4Cp.png"
                    },
                    "name" : "Blätterteigsnäk",
                    "tasteNum" : 0,
                    "time" : {
                        "std" : 0,
                        "min" : 24
                    }
                } 
            ]
        }

## New [/discover/new?recipeNumber={recipeNumber}]
Returns the newest recipes

### Get new [GET]

+ Parameters
    + recipeNumber = `30` (number, optional) ... Maximum number of returned recipes
    
+ Response 200 (application/json)
    
        [ 
            {
                "description" : "Fluffig und saftig,\nherrlich und schmatzig,\nlecker ist dieser Kuchen, \nDu musst nicht länger suchen!",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/3SXvO8rtYh1XR777xfS2.png",
                    "original" : "http://images.anycook.de/recipe/original/3SXvO8rtYh1XR777xfS2.png",
                    "small" : "http://images.anycook.de/recipe/small/3SXvO8rtYh1XR777xfS2.png"
                },
                "name" : "Schokoladen-Beeren-Gugelhupf",
                "time" : {
                    "std" : 1,
                    "min" : 10
                }
            }, 
            {
                "description" : "Gebratener Reis mit Pilzen und Fisch",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/category/nudeln_und_reis.png",
                    "original" : "http://images.anycook.de/recipe/original/category/nudeln_und_reis.png",
                    "small" : "http://images.anycook.de/recipe/small/category/nudeln_und_reis.png"
                },
                "name" : "Nasi Goreng Ikan",
                "time" : {
                    "std" : 1,
                    "min" : 0
                }
            }, 
            {
                "description" : "Quark ist der elementare Bestandteil, aus dem die Atomkern-Bausteine Protonen und Neutronen bestehen sowie der Belag des Kuchens. Sie gelten heute als die fundamentalen Bausteine, aus denen alle Materie aufgebaut ist und mit dem Kakaoteig zusammen ergeben sie einen super leckeren Kuchen.",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/GlIrXIWUaH10JchOuKV3.png",
                    "original" : "http://images.anycook.de/recipe/original/GlIrXIWUaH10JchOuKV3.png",
                    "small" : "http://images.anycook.de/recipe/small/GlIrXIWUaH10JchOuKV3.png"
                },
                "name" : "Russischer Zupfkuchen",
                "time" : {
                    "std" : 1,
                    "min" : 20
                }
            }
        ]

## Recommended [/discover/recommended?recipeNumber={recipeNumber}]
If logged-in it returns the recipes that are similar to the recipes you like. Otherwise it returns the most viewed recipes.

### Get recommended [GET]

+ Parameters
    + recipeNumber = `30` (number, optional) ... Maximum number of returned recipes
    
+ Response 200 (application/json)

        [ 
            {
                "description" : "Fluffig und saftig,\nherrlich und schmatzig,\nlecker ist dieser Kuchen, \nDu musst nicht länger suchen!",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/3SXvO8rtYh1XR777xfS2.png",
                    "original" : "http://images.anycook.de/recipe/original/3SXvO8rtYh1XR777xfS2.png",
                    "small" : "http://images.anycook.de/recipe/small/3SXvO8rtYh1XR777xfS2.png"
                },
                "name" : "Schokoladen-Beeren-Gugelhupf",
                "time" : {
                    "std" : 1,
                    "min" : 10
                }
            }, 
            {
                "description" : "Gebratener Reis mit Pilzen und Fisch",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/category/nudeln_und_reis.png",
                    "original" : "http://images.anycook.de/recipe/original/category/nudeln_und_reis.png",
                    "small" : "http://images.anycook.de/recipe/small/category/nudeln_und_reis.png"
                },
                "name" : "Nasi Goreng Ikan",
                "time" : {
                    "std" : 1,
                    "min" : 0
                }
            }, 
            {
                "description" : "Quark ist der elementare Bestandteil, aus dem die Atomkern-Bausteine Protonen und Neutronen bestehen sowie der Belag des Kuchens. Sie gelten heute als die fundamentalen Bausteine, aus denen alle Materie aufgebaut ist und mit dem Kakaoteig zusammen ergeben sie einen super leckeren Kuchen.",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/GlIrXIWUaH10JchOuKV3.png",
                    "original" : "http://images.anycook.de/recipe/original/GlIrXIWUaH10JchOuKV3.png",
                    "small" : "http://images.anycook.de/recipe/small/GlIrXIWUaH10JchOuKV3.png"
                },
                "name" : "Russischer Zupfkuchen",
                "time" : {
                    "std" : 1,
                    "min" : 20
                }
            }
        ]

## Tasty [/discover/tasty?recipeNumber={recipeNumber}]
Returns the recipes that the users like most.

### Get tasty [GET]

+ Parameters
    + recipeNumber = `30` (number, optional) ... Maximum number of returned recipes
    
+ Response 200 (application/json)

        [ 
            {
                "description" : "Fluffig und saftig,\nherrlich und schmatzig,\nlecker ist dieser Kuchen, \nDu musst nicht länger suchen!",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/3SXvO8rtYh1XR777xfS2.png",
                    "original" : "http://images.anycook.de/recipe/original/3SXvO8rtYh1XR777xfS2.png",
                    "small" : "http://images.anycook.de/recipe/small/3SXvO8rtYh1XR777xfS2.png"
                },
                "name" : "Schokoladen-Beeren-Gugelhupf",
                "time" : {
                    "std" : 1,
                    "min" : 10
                }
            }, 
            {
                "description" : "Gebratener Reis mit Pilzen und Fisch",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/category/nudeln_und_reis.png",
                    "original" : "http://images.anycook.de/recipe/original/category/nudeln_und_reis.png",
                    "small" : "http://images.anycook.de/recipe/small/category/nudeln_und_reis.png"
                },
                "name" : "Nasi Goreng Ikan",
                "time" : {
                    "std" : 1,
                    "min" : 0
                }
            }, 
            {
                "description" : "Quark ist der elementare Bestandteil, aus dem die Atomkern-Bausteine Protonen und Neutronen bestehen sowie der Belag des Kuchens. Sie gelten heute als die fundamentalen Bausteine, aus denen alle Materie aufgebaut ist und mit dem Kakaoteig zusammen ergeben sie einen super leckeren Kuchen.",
                "image" : {
                    "big" : "http://images.anycook.de/recipe/big/GlIrXIWUaH10JchOuKV3.png",
                    "original" : "http://images.anycook.de/recipe/original/GlIrXIWUaH10JchOuKV3.png",
                    "small" : "http://images.anycook.de/recipe/small/GlIrXIWUaH10JchOuKV3.png"
                },
                "name" : "Russischer Zupfkuchen",
                "time" : {
                    "std" : 1,
                    "min" : 20
                }
            }
        ]



